from datetime import datetime
import re

with open("alerts/auth-log-sample.txt", "r") as file:
    log_data = file.read()

log_lower = log_data.lower()

failed_password_count = log_lower.count("failed password")
authentication_failure_count = log_lower.count("authentication failure")
invalid_user_count = log_lower.count("invalid user")
sudo_count = log_lower.count("sudo")

users = re.findall(r"user\s+([a-zA-Z0-9_-]+)", log_data)
unique_users = sorted(set(users))

risk_score = 0
findings = []

if failed_password_count > 0:
    findings.append(f"Failed password attempts detected: {failed_password_count}")
    risk_score += failed_password_count * 2

if authentication_failure_count > 0:
    findings.append(f"Authentication failures detected: {authentication_failure_count}")
    risk_score += authentication_failure_count * 2

if invalid_user_count > 0:
    findings.append(f"Invalid username attempts detected: {invalid_user_count}")
    risk_score += invalid_user_count * 3

if sudo_count > 0:
    findings.append(f"Sudo/admin activity detected: {sudo_count}")
    risk_score += sudo_count

if risk_score >= 15:
    risk_level = "High"
elif risk_score >= 5:
    risk_level = "Medium"
else:
    risk_level = "Low"

report = []

report.append("===== AI SOC ASSISTANT REPORT =====")
report.append(f"Generated: {datetime.now()}")
report.append("")
report.append("Incident Summary:")
report.append("This report analyzes Linux authentication logs for suspicious login and administrative activity.")
report.append("")
report.append(f"Risk Score: {risk_score}")
report.append(f"Risk Level: {risk_level}")
report.append("")

report.append("Findings:")
if findings:
    for finding in findings:
        report.append(f"- {finding}")
else:
    report.append("- No suspicious authentication activity detected.")

report.append("")
report.append("Usernames Identified:")
if unique_users:
    for user in unique_users:
        report.append(f"- {user}")
else:
    report.append("- No usernames extracted.")

report.append("")
report.append("MITRE ATT&CK Mapping:")
if failed_password_count > 0 or authentication_failure_count > 0:
    report.append("- T1110: Brute Force")
if invalid_user_count > 0:
    report.append("- T1078: Valid Accounts / Account Discovery Indicators")
if sudo_count > 0:
    report.append("- T1548: Abuse Elevation Control Mechanism")

report.append("")
report.append("Recommended Investigation Steps:")
report.append("- Review failed login usernames")
report.append("- Check whether invalid usernames were attempted")
report.append("- Review sudo/admin activity for legitimacy")
report.append("- Look for repeated failures in a short time window")
report.append("- Check source IP addresses if SSH activity is present")
report.append("- Consider firewall blocking if brute force activity is confirmed")

report.append("")
report.append("Analyst Notes:")
report.append("- This report was generated by a Python-based SOC automation tool.")
report.append("- Future versions will include AI-generated summaries, IP enrichment, and threat intelligence lookups.")

for line in report:
    print(line)

timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
output_file = f"outputs/report-{timestamp}.txt"

with open(output_file, "w") as file:
    for line in report:
        file.write(line + "\n")

print(f"\nReport saved to: {output_file}")
